### ISSUE TITLE
NameError: global name 'magic' is not defined

### ISSUE THREAD

**Issue by zhangineer2** [datacenter/BRKACI-2945-CLUS#2]
getting the following error after running the build script. Any ideas ?

2018-06-18T12:43:44 packaging application
Traceback (most recent call last):
  File "/tmp/appbuild//CLUS.build/cisco_aci_app_tools-1.1_min/tools/aci_app_packager.py", line 380, in <module>
    rc = packager.main(args.file_path, scriptDir, outputDir, args.private_key_path, args.validate_only)
  File "/tmp/appbuild//CLUS.build/cisco_aci_app_tools-1.1_min/tools/aci_app_packager.py", line 302, in main
    rc, msg = validator.checkMandatoryFiles(self.inputAppDir,"packager",appState,scriptDir=self.scriptDir)
  File "/private/tmp/appbuild/CLUS.build/cisco_aci_app_tools-1.1_min/tools/aci_app_validator.py", line 659, in checkMandatoryFiles
    fileType=magic.from_file(readme[0])
NameError: global name 'magic' is not defined

**Comment by agccie** [comment]
There's a requirement for the packager for libmagic.  This isn't a python package that can't be displayed via pip, it needs to be manually installed (I believe it's available by default on most unix distributions).

This is hidden in the **cisco_aci_app_tools-1.1** README.  I believe you may also be able to workaround this with [https://github.com/ahupp/python-magic](https://github.com/ahupp/python-magic) (although I haven't tested it)

Requirements
---------------------------------------------------------------
A few libraries and commands need to be installed prior to the usage of the tools.
- python-dev
        - On UNIX: apt-get install python-dev

- libmagic
        - On MacOS: Use the packet manager "Homebrew":
                                $ brew install libmagic
- 'zip'
        - On UNIX: apt-get install zip

**Comment by zhangineer2** [comment]
Thank you Andy, this helped resolve my issue
